### ISSUE TITLE
UnicodeDecodeError, for reading a .las file

### ISSUE THREAD

**Issue by JacobGeoGeek** [josestg/Las-converter#3]
**Describe the bug**
In short, I'm trying to convert a `.las` to a `.json` file. after I called the `set_file('SOME-FILE.las)` with the Las-converter tool, UnicodeDecodeError appears. (FYI I'm using the terminal with python 3.9.1) 

**Screenshots from the terminal**

```
>>> from LAS import Converter
>>> c = Converter()
>>> log = c.set_file("SOME-FILE.las")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/LAS/converter.py", line 64, in set_file
    self.__lines = f.readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 131: invalid start byte
```
**Desktop (please complete the following information):**
 - OS:  MacOS Big Sur Version 11.2.3

**Comment by fluviotect** [comment]
I'm having a similar issue at the sam stage. Running: Jupyter Lab in Python 3.7 on a Win7 x64 machine

---------------------------------------------------------------------------```

> 
> UnicodeDecodeError                        Traceback (most recent call last)
> <ipython-input-12-4120979e61dd> in <module>
>       1 c = Converter() # create converter object
>       2 
> ----> 3 log = c.set_file(path+file_las) #return LogWrapper
> 
> C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\LAS\converter.py in set_file(self, file)
>      62             raise Exception("File format no supported!")
>      63         with open(file, "r") as f:
> ---> 64             self.__lines = f.readlines()
>      65         return self.__convert()  # read all lines from data
>      66 
> 
> C:\ProgramData\Anaconda3\envs\py37\lib\encodings\cp1252.py in decode(self, input, final)
>      21 class IncrementalDecoder(codecs.IncrementalDecoder):
>      22     def decode(self, input, final=False):
> ---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>      24 
>      25 class StreamWriter(Codec,codecs.StreamWriter):
> 
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 536: character maps to <undefined>

```
